version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    command: >
      gunicorn main:app 
      -w 36 
      -k uvicorn.workers.UvicornWorker 
      --bind 0.0.0.0:8080 
      --worker-connections 2000 
      --max-requests 100000 
      --max-requests-jitter 10000 
      --timeout 300 
      --backlog 4096 
      --preload
    depends_on:
      - redis
      - celery-worker
    environment:
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2

  celery-worker:
    build: .
    command: >
      celery -A app.tasks worker 
      --loglevel=info 
      --concurrency=8 
      --max-tasks-per-child=1000
      --pool=prefork
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2

  celery-beat:
    build: .
    command: celery -A app.tasks beat --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"