[default]
GEE_SERVICE_ACCOUNT_FILE='/app/.service-accounts/gee.json'
LIFESPAN_URL = 24  # Aumentado para 24 horas

# Cache híbrido
REDIS_URL = 'redis://valkey:6379'
S3_ENDPOINT = 'http://minio:9000'
S3_ACCESS_KEY = 'minioadmin'
S3_SECRET_KEY = 'minioadmin'
S3_BUCKET = 'tiles-cache'

# Performance
WORKERS = 20  # Ajustar baseado em CPUs disponíveis
WORKER_CONNECTIONS = 2000
MAX_REQUESTS = 20000
MAX_REQUESTS_JITTER = 1000

# Rate limiting - aumentado para suportar carregamento de múltiplos anos/tiles
RATE_LIMIT_PER_MINUTE = 100000  # Por IP - para tiles Landsat/Sentinel
RATE_LIMIT_BURST = 10000

# Celery Configuration
CELERY_BROKER_URL = 'redis://valkey:6379/1'
CELERY_RESULT_BACKEND = 'redis://valkey:6379/2'