version: '3.8'

name: tile-lapig

services:
  tile-local:
    image: lapig/app_tile:prod_latest
    hostname: tile-local
    container_name: tile-local
    privileged: true
    deploy:
      resources:
        limits:
          memory: 4G  # Aumentado para suportar mais carga
        reservations:
          memory: 2G
    environment:
      - TILES_ENV=production
      - REDIS_URL=redis://valkey:6379
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - '/etc/localtime:/etc/localtime'
      - './.service-accounts/gee.json:/app/.service-accounts/gee.json'
      - './cache:/app/cache'  # Cache local para hot tiles
    depends_on:
      - valkey
      - minio
  
  valkey:
    image: 'valkey/valkey:7.2.5'
    hostname: valkey
    container_name: valkey
    command: >
      valkey-server
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    ports:
      - '6379:6379'
    volumes:
      - 'valkey-data:/data'
    restart: always

  minio:
    image: minio/minio:latest
    hostname: minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio-data:/data'
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:alpine
    hostname: nginx
    container_name: nginx-cache
    ports:
      - '80:80'
    volumes:
      - './config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - 'nginx-cache:/var/cache/nginx'
    depends_on:
      - tile-local
    restart: always

volumes:
  valkey-data:
  minio-data:
  nginx-cache:
