
version: '3.8'

name: tile-services

services:
  valkey:
    image: 'valkey/valkey:7.2.5'
    hostname: valkey
    container_name: valkey-local
    command: >
      valkey-server
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    ports:
      - '6379:6379'
    volumes:
      - 'valkey-data:/data'
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    hostname: minio
    container_name: minio-local
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio-data:/data'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  valkey-data:
  minio-data: